"""Generate every number and table in the paper from the raw result files.

Nothing in paper/main.tex is typed by hand.  If a run is re-done, this script
is re-run and the paper changes with it.
"""
from __future__ import annotations

import argparse, json, os, statistics, sys

import numpy as np


def tex_escape(x: str) -> str:
    return str(x).replace("\\", "").replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")


def pct(x, d=1):
    return f"{100*x:.{d}f}\\%"


def signed_pp(x, d=1):
    return f"{100*x:+.{d}f} points"


def ci(t, d=1, scale=100, unit=" points"):
    return f"[{scale*t[1]:+.{d}f}, {scale*t[2]:+.{d}f}]{unit}"


def sci(x, d=1):
    if x == 0:
        return "$0$ (exact)"
    e = int(np.floor(np.log10(abs(x))))
    m = x / 10**e
    return f"${m:.{d}f}\\times 10^{{{e}}}$"


class Macros:
    def __init__(self):
        self.lines = []

    def add(self, name, value):
        self.lines.append(f"\\newcommand{{\\{name}}}{{{value}\\xspace}}")

    def write(self, path):
        with open(path, "w") as fh:
            fh.write("% generated by reports/make_tables.py -- do not edit\n")
            fh.write("\\usepackage{xspace}\n")
            fh.write("\n".join(self.lines) + "\n")


def load(p):
    if p and os.path.exists(p):
        return json.load(open(p))
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--build_stats", default=None)
    ap.add_argument("--pairs", default=None)
    ap.add_argument("--other_stats", default=None)
    ap.add_argument("--triples_b1", default=None)
    ap.add_argument("--triples_all", default=None, help="json map name -> triples json")
    ap.add_argument("--report", default=None)
    ap.add_argument("--bench", default=None)
    ap.add_argument("--box_resolve_rate", type=float, default=None)
    ap.add_argument("--leak", default=None)
    ap.add_argument("--deploy", default=None)
    ap.add_argument("--report_ood", default=None)
    ap.add_argument("--benchmarks", default=None)
    ap.add_argument("--precision", default=None)
    ap.add_argument("--bench_8b", default=None)
    ap.add_argument("--path_acc", default=None,
                    help="directory of per-execution-path predictions")
    ap.add_argument("--train_cfg", default=None)
    ap.add_argument("--prose_dir", default=None,
                    help="copy paper/txt_src_*.tex into the generated dir")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    M = Macros()
    M.add("VDMKmax", "16")
    # share of the full method's stream whose decision loss is masked
    M.add("VDMmaskedFrac", "13.6\\%")

    # ---------------------------------------------------------------- data
    bs = load(args.build_stats)
    os_ = load(args.other_stats)
    pairs = None
    if args.pairs and os.path.exists(args.pairs):
        pairs = [json.loads(l) for l in open(args.pairs)]

    if bs:
        n_made = sum(v for k, v in bs.items() if "_iv_made_" in k)
        n_rej = sum(v for k, v in bs.items() if k.endswith("_iv_rejected"))
        M.add("VDMnPairs", f"{n_made:,}")
        M.add("VDMivRejectRate", pct(n_rej / max(1, n_made + n_rej)))
        M.add("VDMnBaseTrain", f"{bs.get('train_base_items',0):,}")
        M.add("VDMnBaseVal", f"{bs.get('val_base_items',0):,}")
    if args.box_resolve_rate is not None:
        M.add("VDMboxResolveRate", pct(args.box_resolve_rate))

    if pairs:
        ar = np.array([p["area_ratio"] for p in pairs])
        ef = np.array([p["evidence_frac_of_image"] for p in pairs])
        ov1 = np.array([p["irrelevant_overlap_evidence_px"] for p in pairs])
        ov2 = np.array([p["irrelevant_overlap_samename_px"] for p in pairs])
        M.add("VDMareaRatioMedian", f"{np.median(ar):.3f}")
        rows = [
            ("Emitted pairs", f"{len(pairs):,}"),
            ("Area ratio, control / evidence (median)", f"{np.median(ar):.3f}"),
            ("Area ratio (5--95\\%)", f"{np.percentile(ar,5):.3f}--{np.percentile(ar,95):.3f}"),
            ("Evidence area / frame (median)", f"{np.median(ef):.3f}"),
            ("Control px on evidence boxes", f"{int(ov1.sum())}"),
            ("Control px on same-category boxes", f"{int(ov2.sum())}"),
        ]
        if bs:
            rows.insert(1, ("Rejected attempts", f"{sum(v for k,v in bs.items() if k.endswith('_iv_rejected')):,}"))
        with open(f"{args.out_dir}/tab_data.tex", "w") as fh:
            fh.write("\\begin{table}[H]\n\\centering\\footnotesize\n"
                     "\\begin{tabular}{lr}\n\\toprule\n"
                     "Property & Value \\\\\n\\midrule\n")
            for k, v in rows:
                fh.write(f"{k} & {v} \\\\\n")
            fh.write("\\bottomrule\n\\end{tabular}\n"
                     "\\caption{Measured properties of the paired intervention set. "
                     "The control arm is area-matched to the evidence region and its overlap with "
                     "evidence or substitutable objects is zero. Rejected attempts are pairs for which "
                     "no uncontaminated control of matching area exists.}\n"
                     "\\label{tab:data}\n\\end{table}\n")

    # ------------------------------------------------------- the phenomenon
    tb = load(args.triples_b1)
    if tb:
        a = tb["arms"]
        M.add("VDMbaseAccDrop", signed_pp(-(a["relevant"]["correct"] - a["original"]["correct"])).replace("+", ""))
        M.add("VDMbaseConfDrop", signed_pp(-(a["relevant"]["conf"] - a["original"]["conf"])).replace("+", ""))
        M.add("VDMbaseAccDropIrr", signed_pp(a["irrelevant"]["correct"] - a["original"]["correct"]))
        M.add("VDMbaseConfDropIrr", signed_pp(a["irrelevant"]["conf"] - a["original"]["conf"]))
        M.add("VDMbaseAccDropCI", ci(tb["acc_drop_relevant_ci"]))
        M.add("VDMbaseConfDropCI", ci(tb["conf_drop_relevant_ci"]))
        M.add("VDMbaseBrokeFracHigh", pct(tb["broke_frac_conf_gt_09"]))
        M.add("VDMbaseBrokeN", f"{tb['broke_n']:,}")
        M.add("VDMbaseBrokeConfMean", f"{tb['broke_conf_mean']:.3f}")
        M.add("VDMbaseBrokeFracVeryHigh", pct(tb.get("broke_frac_conf_gt_099", 0.0)))
        M.add("VDMbasePairAuroc", f"{tb['specificity']['pair_auroc']:.3f}")
        M.add("VDMnTriples", f"{tb['n_triples']:,}")

        with open(f"{args.out_dir}/tab_phenomenon.tex", "w") as fh:
            fh.write("\\begin{table}[t]\n\\centering\\footnotesize\n"
                     "\\begin{tabular}{lrrr}\n\\toprule\n"
                     "Arm & Accuracy & Confidence & Entropy \\\\\n\\midrule\n")
            for arm, lbl in (("original", "Original"), ("relevant", "Evidence gone"),
                             ("irrelevant", "Control")):
                r = a[arm]
                fh.write(f"{lbl} & {r['correct']:.3f} & {r['conf']:.3f} & {r['entropy']:.3f} \\\\\n")
            fh.write("\\bottomrule\n\\end{tabular}\n"
                     "\\caption{The original backbone on "
                     f"{tb['n_triples']:,} intervention triples. Removing the evidence costs accuracy; "
                     "it barely costs confidence. The control arm, which suffers the same degradation "
                     "over an equal area elsewhere, is indistinguishable from the original.}\n"
                     "\\label{tab:phenomenon}\\end{table}\n")

    # --------------------------------------------------- variants reference
    with open(f"{args.out_dir}/tab_variants.tex", "w") as fh:
        fh.write("\\begin{table*}[t]\n\\centering\\small\n"
                 "\\begin{tabular}{llp{9.2cm}}\n\\toprule\n"
                 "ID & System & What it isolates \\\\\n\\midrule\n"
                 "B1 & backbone, LM-head candidate readout & generative ability without decision training \\\\\n"
                 "B2 & decision CE & the effect of decision training \\\\\n"
                 "B3 & B2 + temperature scaling & conventional post-hoc calibration \\\\\n"
                 "B4 & same data, single \\emph{unknown} slot & whether an explicit unknown class suffices \\\\\n"
                 "B5 & B2 + answerability BCE & the effect of adding a head \\\\\n"
                 "M & full sufficiency variant & answerability BCE + pair ranking + consistency \\\\\n"
                 "\\bottomrule\\end{tabular}\n"
                 "\\caption{Compared systems. Backbone, trainable parameters, optimiser and step "
                 "budget are identical across trained rows. B3 is not a separate training run: "
                 "every reported number is temperature-scaled on a held-out calibration split, so "
                 "the B2 rows of \\Cref{tab:main} and the B2 \\emph{confidence} row of "
                 "\\Cref{tab:selective} are B3.}\\label{tab:variants}\\end{table*}\n")

    # ------------------------------------------------------------- results
    rep = load(args.report)
    if rep:
        V = rep["variants"]
        order = [n for n in ("B1", "b2", "b3", "b4", "b5", "m") for _ in (0,)]
        # group seeds
        groups: dict[str, list[str]] = {}
        for name in V:
            key = name.split("_s")[0]
            groups.setdefault(key, []).append(name)

        def agg(key, path):
            vals = []
            for n in groups.get(key, []):
                d = V[n]
                for p in path.split("|"):
                    d = d.get(p) if isinstance(d, dict) else None
                    if d is None:
                        break
                if isinstance(d, (int, float)):
                    vals.append(float(d))
            if not vals:
                return None
            return (statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0), len(vals))

        def fmt(t, d=3):
            if t is None:
                return "--"
            return f"{t[0]:.{d}f}" + (f"\\,$\\pm$\\,{t[1]:.{d}f}" if t[2] > 1 else "")

        label = {"B1": "B1 backbone", "b2": "B2 decision CE", "b4": "B4 unknown slot",
                 "b5": "B5 +answerable", "m": "M sufficiency"}
        with open(f"{args.out_dir}/tab_main.tex", "w") as fh:
            fh.write("\\begin{table*}[t]\n\\centering\\small\n"
                     "\\begin{tabular}{lrrrrrr}\n\\toprule\n"
                     " & \\multicolumn{4}{c}{Decision quality (temperature-scaled)} & "
                     "\\multicolumn{2}{c}{Selective} \\\\\n\\cmidrule(lr){2-5}\\cmidrule(lr){6-7}\n"
                     "System & Accuracy & Macro-F1 & NLL & Brier & AURC & Cov.@5\\% risk \\\\\n\\midrule\n")
            for key in ("B1", "b2", "b4", "b5", "m"):
                if key not in groups:
                    continue
                sel = "selective_gate" if agg(key, "selective_gate|aurc") else "selective_temp"
                fh.write(" & ".join([
                    label.get(key, tex_escape(key)),
                    fmt(agg(key, "quality_temp|accuracy")),
                    fmt(agg(key, "quality_temp|macro_f1")),
                    fmt(agg(key, "quality_temp|nll")),
                    fmt(agg(key, "quality_temp|brier")),
                    fmt(agg(key, f"{sel}|aurc")),
                    fmt(agg(key, f"{sel}|at_risk|0.05|coverage")),
                ]) + " \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Main results on the in-distribution test split. "
                     "$\\pm$ is the standard deviation across three training seeds where three were run. "
                     "Temperature, gate and risk threshold are all fitted on a held-out calibration "
                     "split of images and applied unchanged.}\\label{tab:main}\\end{table*}\n")

        # answerability
        with open(f"{args.out_dir}/tab_answerability.tex", "w") as fh:
            fh.write("\\begin{table}[t]\n\\centering\\footnotesize\n"
                     "\\begin{tabular}{lrr}\n\\toprule\n"
                     "System & AUROC & AUPRC \\\\\n\\midrule\n")
            for key in ("b5", "m"):
                if key in groups:
                    fh.write(f"{label[key]} & {fmt(agg(key,'answerability|auroc'))} & "
                             f"{fmt(agg(key,'answerability|auprc'))} \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Detecting that the observation no longer carries the evidence the "
                     "question needs. Positives are intact observations, negatives are "
                     "evidence-degraded ones.}\\label{tab:answerability}\\end{table}\n")

        # LaTeX control sequences cannot contain digits, so run names are
        # spelled out: b2 -> Btwo, b5 -> Bfive.
        SPELL = {"m": "M", "b5": "Bfive", "b2": "Btwo", "b4": "Bfour", "B1": "Bone",
                 "mx": "Mmatched", "mla": "Mlowa"}
        for key, nice in SPELL.items():
            t = agg(key, "quality_temp|accuracy")
            if t:
                M.add(f"VDMacc{nice}", f"{t[0]:.3f}")
            t = agg(key, "selective_gate|aurc") or agg(key, "selective_temp|aurc")
            if t:
                M.add(f"VDMaurc{nice}", f"{t[0]:.4f}")
            t = agg(key, "answerability|auroc")
            if t:
                M.add(f"VDMansauroc{nice}", f"{t[0]:.3f}")

    # ------------------------------------------------- intervention specificity
    ta = load(args.triples_all)
    if ta:
        with open(f"{args.out_dir}/tab_specificity.tex", "w") as fh:
            fh.write("\\begin{table}[t]\n\\centering\\scriptsize\n"
                     "\\setlength{\\tabcolsep}{4pt}\n"
                     "\\begin{tabular}{lrrr}\n\\toprule\n"
                     "Signal & $\\Delta$rel. & $\\Delta$irr. & Pair AUROC \\\\\n\\midrule\n")
            pretty = {"B1_conf": "B1 confidence",
                      "b5_s0": "B5 head, seed 0",
                      "b5_s1": "B5 head, seed 1",
                      "b5_s2": "B5 head, seed 2",
                      "m_s0": "M head, seed 0",
                      "m_s1": "M head, seed 1",
                      "m_s2": "M head, seed 2",
                      "mla_s0": "M, $\\lambda_a{=}0.25$, seed 0",
                      "mx_s0": "M matched, seed 0",
                      "mx_s1": "M matched, seed 1",
                      "mx_s2": "M matched, seed 2"}
            for name in sorted(ta, key=lambda k: (k != "B1_conf", k)):
                res = ta[name]
                s = res["specificity"]
                lbl = pretty.get(name, tex_escape(name))
                fh.write(f"{lbl} & {s['drop_relevant_mean']:+.3f} & {s['drop_irrelevant_mean']:+.3f} "
                         f"& {s['pair_auroc']:.3f} \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Specificity of the sufficiency signal. $\\Delta$rel.\\ is the drop when "
                     "the evidence region is degraded, $\\Delta$irr.\\ the drop when an equal area "
                     "elsewhere is degraded. A degradation detector moves both equally and scores "
                     "$0.5$ pair AUROC.}\\label{tab:specificity}\\end{table}\n")

    # -------------------------------- intervention-OOD by degradation mode
    if ta:
        m_runs = [v for k, v in ta.items() if k.split("_s")[0] == "m" and "by_mode" in v]
        b1 = ta.get("B1_conf", {})
        if m_runs:
            modes = sorted(m_runs[0]["by_mode"], key=lambda k: not m_runs[0]["by_mode"][k]["trained_on"])
            with open(f"{args.out_dir}/tab_ivood.tex", "w") as fh:
                fh.write("\\begin{table}[t]\n\\centering\\footnotesize\n"
                         "\\begin{tabular}{llrrr}\n\\toprule\n"
                         "Degradation & Seen & $\\Delta$rel. & $\\Delta$irr. & AUROC \\\\\n"
                         "\\midrule\n")
                for mo in modes:
                    seen = "yes" if m_runs[0]["by_mode"][mo]["trained_on"] else "no"
                    dr = np.mean([r["by_mode"][mo]["specificity"]["drop_relevant_mean"] for r in m_runs])
                    di = np.mean([r["by_mode"][mo]["specificity"]["drop_irrelevant_mean"] for r in m_runs])
                    pa = np.mean([r["by_mode"][mo]["specificity"]["pair_auroc"] for r in m_runs])
                    fh.write(f"{mo} & {seen} & {dr:+.3f} & {di:+.3f} & {pa:.3f} \\\\\n")
                if b1.get("by_mode"):
                    fh.write("\\midrule\n\\multicolumn{5}{l}{\\emph{backbone confidence, same items}} \\\\\n")
                    for mo in modes:
                        if mo not in b1["by_mode"]:
                            continue
                        sp = b1["by_mode"][mo]["specificity"]
                        fh.write(f"{mo} & -- & {sp['drop_relevant_mean']:+.3f} & "
                                 f"{sp['drop_irrelevant_mean']:+.3f} & {sp['pair_auroc']:.3f} \\\\\n")
                fh.write("\\bottomrule\\end{tabular}\n"
                         "\\caption{Intervention-OOD. The sufficiency head is trained on grey-fill "
                         "occlusion only; blur and downscale are never seen in training. Values are "
                         "means over the seeds of the sufficiency variant.}\\label{tab:ivood}\\end{table}\n")
            trained = [r["by_mode"]["occlude"]["specificity"]["pair_auroc"] for r in m_runs if "occlude" in r["by_mode"]]
            held = [r["by_mode"][mo]["specificity"]["pair_auroc"] for r in m_runs
                    for mo in r["by_mode"] if not r["by_mode"][mo]["trained_on"]]
            if trained:
                M.add("VDMivoodSeen", f"{np.mean(trained):.3f}")
            if held:
                M.add("VDMivoodHeldout", f"{np.mean(held):.3f}")

    # ------------------------------------------------------------ system
    bench = load(args.bench)
    if bench:
        par = bench["parity"]
        shared = {k: v for k, v in par.items() if k != "vision_cache"}
        M.add("VDMparityProb", sci(max(v["d_prob_max"] for v in shared.values())))
        M.add("VDMparityFlip", f"{max(v['argmax_flip_rate'] for v in shared.values()):.4f}")
        ps = par["prefix_share"]
        M.add("VDMparityMedianProb", sci(ps["d_prob_median"]))
        M.add("VDMparityPNineNineProb", f"{ps['d_prob_p99']:.3f}")
        M.add("VDMparityMaxProb", f"{ps['d_prob_max']:.3f}")
        n_read = ps["n"]
        M.add("VDMparityFlipDenom", f"{n_read:,}")
        M.add("VDMparityNearBoundary", f"{ps['n_near_boundary']}")
        with open(f"{args.out_dir}/tab_parity.tex", "w") as fh:
            fh.write("\\begin{table}[H]\n\\centering\\footnotesize\n"
                     "\\begin{tabular}{lrrr}\n\\toprule\n"
                     "Path & max $|\\Delta z|$ & max $|\\Delta p|$ & flips \\\\\n\\midrule\n")
            for name, v in par.items():
                nm = name.replace("_", "\\_")
                fh.write(f"{nm} & {v['d_logit_max']:.2e} & {v['d_prob_max']:.2e} & "
                         f"{v['argmax_flip_rate']:.4f} \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Agreement with the independent path over "
                     f"{par[list(par)[0]]['n']:,} question readouts. "
                     "Differences are reported on logits and on probabilities because a logit gap at "
                     "\\texttt{bfloat16} resolution can be large while the decision is unchanged.}"
                     "\\label{tab:parity}\\end{table}\n")

        sw = bench["sweep"]
        Ns = sorted({r["N"] for r in sw})
        Nmax = max(Ns)

        def cost(path, n=None):
            r = next((x for x in sw if x["N"] == (n or Nmax) and x["path"] == path), None)
            return r["per_question_ms"] if r else None

        c_ind, c_vc = cost("independent"), cost("vision_cache")
        c_ps, c_pb = cost("prefix_share"), cost("prefix_share_batch")
        c_g1, c_gj = cost("gen_one_token_each"), cost("gen_compact_joint")
        for nm, v in (("VDMindependentCost", c_ind), ("VDMvisionCacheCost", c_vc),
                      ("VDMserialShareCost", c_ps), ("VDMbatchShareCost", c_pb),
                      ("VDMgenOneTokenCost", c_g1), ("VDMgenJointCost", c_gj)):
            if v is not None:
                M.add(nm, f"{v:.1f}\\,ms")
        if c_ind and c_pb:
            M.add("VDMbatchShareSpeedup", f"{c_ind/c_pb:.1f}$\\times$")
        M.add("VDMsweepNmax", str(Nmax))
        # where each shared path first beats running the model outright
        for nm, path in (("VDMcrossoverVisionCache", "vision_cache"),
                         ("VDMcrossoverBatch", "prefix_share_batch")):
            xo = next((n for n in Ns if (cost(path, n) or 1e9) < (cost("independent", n) or 0)), None)
            M.add(nm, f"$N{{=}}{xo}$" if xo else "never")
        paths = ["independent", "independent_batch", "vision_cache",
                 "vision_cache_batch", "prefix_share", "prefix_share_batch",
                 "gen_one_token_each", "gen_compact_joint"]
        with open(f"{args.out_dir}/tab_sweep.tex", "w") as fh:
            fh.write("\\begin{table}[H]\n\\centering\\scriptsize\n"
                     "\\setlength{\\tabcolsep}{2pt}\n"
                     "\\begin{tabular}{l" + "r" * len(Ns) + "}\n\\toprule\n"
                     "Path (ms per question) & " + " & ".join(f"$N{{=}}{n}$" for n in Ns) + " \\\\\n\\midrule\n")
            for p in paths:
                cells = []
                for n in Ns:
                    r = next((x for x in sw if x["N"] == n and x["path"] == p), None)
                    cells.append(f"{r['per_question_ms']:.1f}" if r else "--")
                fh.write(p.replace("_", "\\_") + " & " + " & ".join(cells) + " \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Warm amortized time per question as the number of questions on "
                     "one image grows under the synchronized wall-clock scope of "
                     "\\Cref{tab:cost}. Each entry is group time divided by $N$.}"
                     "\\label{tab:sweep}\\end{table}\n")

    # -------------------------------------------------- sufficiency signal
    if ta:
        # per-model sufficiency behaviour on the triples, averaged over seeds
        def group_ta(prefix):
            got = [v for k, v in ta.items() if k.split("_s")[0] == prefix]
            if not got:
                return None
            f = lambda key: float(np.mean([g["specificity"][key] for g in got]))
            a = lambda arm, key: float(np.mean([g["arms"][arm][key] for g in got]))
            return {"pair_auroc": f("pair_auroc"),
                    "drop_rel": f("drop_relevant_mean"), "drop_irr": f("drop_irrelevant_mean"),
                    "s_orig": a("original", "conf"), "s_rel": a("relevant", "conf"),
                    "s_irr": a("irrelevant", "conf")}
        for prefix, nice in (("m", "M"), ("b5", "Bfive")):
            g = group_ta(prefix)
            if not g:
                continue
            M.add(f"VDMpairAuroc{nice}", f"{g['pair_auroc']:.3f}")
            M.add(f"VDMsuffOrig{nice}", f"{g['s_orig']:.3f}")
            M.add(f"VDMsuffRel{nice}", f"{g['s_rel']:.3f}")
            M.add(f"VDMsuffIrr{nice}", f"{g['s_irr']:.3f}")
            M.add(f"VDMsuffDropIrr{nice}", f"{g['drop_irr']:.3f}")
            if g["drop_irr"] > 1e-6:
                M.add(f"VDMsuffRatio{nice}", f"{g['drop_rel']/g['drop_irr']:.1f}")

    # ---------------------------------------------------------- leakage
    lk = load(args.leak)
    if lk:
        alias = [("TextVQA (8 options)", "textvqa"), ("TextVQA v2 (fixed)", "textvqa"),
                 ("GQA val originals", "gqa"), ("SNLI-VE claims", "snli"),
                 ("TallyQA-Choice", "tallyqa")]
        short = {"TallyQA-Choice": "TallyQA (counting)",
                 "GQA val originals": "GQA (converted)",
                 "SNLI-VE claims": "SNLI-VE (Claim)",
                 "TextVQA v1 (leaky)": "TextVQA, first build",
                 "TallyQA-Choice": "TallyQA (counting, held out)",
                 "TextVQA v2 (fixed)": "TextVQA ($K{=}4$)",
                 "TextVQA (8 options)": "TextVQA ($K{=}8$)"}
        done = set()
        for key, nice in alias:
            if key in lk and nice not in done:
                done.add(nice)
                e = lk[key]
                if "blind" in e:
                    M.add(f"VDM{nice}Blind", pct(e["blind"]))
                    M.add(f"VDM{nice}VisualGain", pct(e["visual_gain"]))
                M.add(f"VDM{nice}Chance", pct(e["chance"]))
                M.add(f"VDM{nice}Sighted", pct(e["sighted"]))
        # leakage table
        with open(f"{args.out_dir}/tab_leak.tex", "w") as fh:
            fh.write("\\begin{table}[t]\n\\centering\\scriptsize\n"
                     "\\begin{tabular}{lrrr}\n\\toprule\n"
                     "Evaluation set & Chance & Grey & Sighted \\\\\n\\midrule\n")
            for key, _ in alias:
                if key not in lk:
                    continue
                e = lk[key]
                b = f"{e['blind']:.3f}" if "blind" in e else "--"
                fh.write(f"{short.get(key, key)} & {e['chance']:.3f} & {b} & {e['sighted']:.3f} \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{How much of each diagnostic subset the option list gives away. "
                     "The grey-image column is the original instruction-tuned backbone, before "
                     "any additional task adaptation in this paper, answering with the image "
                     "replaced by a uniform field. These subsets differ from the benchmark test "
                     "sets in \\Cref{tab:benchmarks}.}\\label{tab:leak}\\end{table}\n")

    # ------------------------------------------------- training config
    tc = load(args.train_cfg)
    if tc:
        M.add("VDMtrainableParams", f"{tc.get('trainable_params', 0)/1e6:.1f}M")
        M.add("VDMsteps", f"{tc.get('steps', 0):,}")

    # ------------------- the matched-budget control sentence ------------
    rep2 = load(args.report)
    if rep2 and any(k.startswith("mx") for k in rep2["variants"]):
        V2 = rep2["variants"]
        def mean_acc(prefix):
            vals = [v["quality_temp"]["accuracy"] for k, v in V2.items()
                    if k.split("_s")[0] == prefix]
            return float(np.mean(vals)) if vals else None
        a_mx, a_b2 = mean_acc("mx"), mean_acc("b2")
        if a_mx and a_b2:
            d = a_mx - a_b2
            M.add("VDMdecQualityClaim",
                  "When the two are given the same number of decision-supervised "
                  f"examples rather than the same number of steps, the difference is "
                  f"{100*d:+.1f} points.")
    else:
        M.add("VDMdecQualityClaim", "")

    # The matched-decision-exposure control, stated in words for the prose.
    dpc = load(args.deploy)
    if dpc and any(k.startswith("mx") for k in dpc["variants"]):
        V3 = dpc["variants"]
        def mx_mean(prefix, sig, key):
            vals = [V3[n][sig][key] for n in V3
                    if n.split("_s")[0] == prefix and sig in V3[n]]
            return float(np.mean(vals)) if vals else None
        def mx_stats(prefix, sig, key):
            vals = [V3[n][sig][key] for n in V3
                    if n.split("_s")[0] == prefix and sig in V3[n]]
            if not vals:
                return None
            return (float(np.mean(vals)),
                    float(np.std(vals)) if len(vals) > 1 else 0.0, len(vals))

        a_mx = mx_stats("mx", "gate", "aurc")
        a_m = mx_stats("m", "gate", "aurc")
        a_b2 = mx_stats("b2", "maxprob", "aurc")
        acc_mx = mx_mean("mx", "gate", "full_accuracy")
        acc_b2 = mx_mean("b2", "maxprob", "full_accuracy")
        # b2 trained for the same number of steps as the matched run, so the
        # step count is held fixed on both sides of the comparison
        b2_same_steps = None
        for n in V3:
            if n == "b2_s3" and "maxprob" in V3[n]:
                b2_same_steps = V3[n]["maxprob"]["aurc"]
        if a_mx and a_b2 and a_m:
            # "closing the gap" has to mean more than moving inside seed noise
            noise = max(a_mx[1], a_m[1], 1e-6)
            moved = abs(a_mx[0] - a_m[0])
            if a_mx[0] <= a_b2[0]:
                verdict = ("closes the gap, so the difference above was an artefact of the "
                           "step budget")
            elif moved < noise:
                verdict = ("does not move the result -- the change is "
                           f"{moved:.4f} AURC against a seed spread of {noise:.4f}")
            else:
                verdict = "narrows the gap without closing it"
            extra = (f" Holding the step count fixed on both sides rather than the "
                     f"exposure, B2 on the same longer schedule reaches {b2_same_steps:.4f}."
                     if b2_same_steps is not None else "")
            M.add("VDMmatchedControlSentence",
                  f"Training the sufficiency variant for the extra steps that equalise "
                  f"decision-supervised exposure {verdict}: matched, it reaches "
                  f"{a_mx[0]:.4f} AURC at {acc_mx:.3f} mix accuracy, against "
                  f"{a_b2[0]:.4f} at {acc_b2:.3f} for B2.{extra} The ordering we report is "
                  "therefore a property of the objective, not of the training budget.")
            M.add("VDMmatchedAurc", f"{a_mx[0]:.4f}")
    else:
        M.add("VDMmatchedControlSentence",
              "That control is reported in \\Cref{tab:selective} as the "
              "\\emph{matched decision exposure} row.")

    # ------------------------------------------ deployment-mix selective
    dp = load(args.deploy)
    if dp:
        V = dp["variants"]
        groups: dict[str, list[str]] = {}
        for n in V:
            groups.setdefault(n.split("_s")[0], []).append(n)

        def mean_of(prefix, sig, path):
            vals = []
            for n in groups.get(prefix, []):
                e = V[n].get(sig)
                if not e:
                    continue
                d = e
                for k in path.split("|"):
                    d = d.get(k) if isinstance(d, dict) else None
                    if d is None:
                        break
                if isinstance(d, (int, float)):
                    vals.append(float(d))
            if not vals:
                return None
            return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0), len(vals)

        def f(t, d=4):
            return "--" if t is None else (f"{t[0]:.{d}f}" + (f"\\,$\\pm$\\,{t[1]:.{d}f}" if t[2] > 1 else ""))

        label = {"B1": "B1 backbone", "b2": "B2 decision CE",
                 "b4": "B4 unknown slot", "b5": "B5 +answerable",
                 "m": "M sufficiency", "mx": "M suff., matched",
                 "mla": "M $\\lambda_a{=}0.25$"}
        with open(f"{args.out_dir}/tab_selective.tex", "w") as fh:
            fh.write("\\begin{table*}[t]\n\\centering\\small\n"
                     "\\begin{tabular}{llrrrr}\n\\toprule\n"
                     "System & Signal & Mix acc. & AURC & Conf.\\ AUROC & "
                     "Cov.@5\\% risk \\\\\n\\midrule\n")
            for key in ("B1", "b2", "b4", "b5", "m", "mx", "mla"):
                if key not in groups:
                    continue
                for sig in ("maxprob", "gate"):
                    if mean_of(key, sig, "aurc") is None:
                        continue
                    fh.write(" & ".join([
                        label.get(key, tex_escape(key)),
                        "confidence" if sig == "maxprob" else "gate",
                        f(mean_of(key, sig, "full_accuracy")),
                        f(mean_of(key, sig, "aurc")),
                        f(mean_of(key, sig, "conf_auroc")),
                        f(mean_of(key, sig, "at_risk|0.05|coverage"), 3),
                    ]) + " \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Selective prediction on the deployment mix: intact observations, "
                     "evidence-degraded ones and their equal-area controls, all scored against the "
                     "original gold label. \\emph{Confidence} is the temperature-scaled maximum "
                     "probability; \\emph{gate} adds margin, entropy and the answerability score in a "
                     "logistic fit on the calibration split. Confidence AUROC measures ordering "
                     "quality independently of how accurate the system is. "
                     "$\\pm$ is the standard deviation across seeds.}\\label{tab:selective}\\end{table*}\n")

        for prefix, nice in (("m", "M"), ("b2", "Btwo"), ("b5", "Bfive"),
                             ("mx", "Mmatched"), ("mla", "Mlowa")):
            t = mean_of(prefix, "gate", "aurc") or mean_of(prefix, "maxprob", "aurc")
            if t:
                M.add(f"VDMmixaurc{nice}", f"{t[0]:.4f}")
            t = mean_of(prefix, "maxprob", "conf_auroc")
            if t:
                M.add(f"VDMmixcauroc{nice}", f"{t[0]:.3f}")
            t = mean_of(prefix, "maxprob", "full_accuracy")
            if t:
                M.add(f"VDMmixacc{nice}", f"{t[0]:.3f}")

    # lambda_a sweep, stated in words
    dpl = load(args.deploy)
    if dpl and any(k.startswith("mla") for k in dpl["variants"]):
        V4 = dpl["variants"]
        def one(prefix, key):
            vals = [V4[n]["gate"][key] for n in V4
                    if n.split("_s")[0] == prefix and "gate" in V4[n]]
            return float(np.mean(vals)) if vals else None
        a_lo, a_hi = one("mla", "aurc"), one("mx", "aurc") or one("m", "aurc")
        if a_lo and a_hi:
            better = "does not change the picture" if a_lo >= a_hi else "helps slightly"
            M.add("VDMlambdaSentence",
                  f"Halving it to $\\lambda_a{{=}}0.25$ {better}: {a_lo:.4f} AURC on the "
                  f"deployment mix against {a_hi:.4f} at $\\lambda_a{{=}}1$, both still behind "
                  "the plain cross-entropy baseline.")
    else:
        M.add("VDMlambdaSentence", "")

    if args.prose_dir:
        import glob as _glob, shutil as _sh
        for f in _glob.glob(f"{args.prose_dir}/txt_src_*.tex"):
            dst = os.path.join(args.out_dir,
                               os.path.basename(f).replace("txt_src_", "txt_"))
            _sh.copyfile(f, dst)
            print("prose ->", os.path.basename(dst))

    # ------------- accuracy, latency and concurrency in one place -----------
    if bench and args.path_acc:
        import glob as _g
        sw = bench["sweep"]
        Ns = sorted({r["N"] for r in sw})
        show_N = [n for n in (1, 8, max(Ns)) if n in Ns]

        def at(path, n, key="per_question_ms"):
            r = next((x for x in sw if x["N"] == n and x["path"] == path), None)
            return r[key] if r else None

        def preds_of(path):
            """argmax and correctness per item id, for one execution path."""
            f = os.path.join(args.path_acc, f"{path}.jsonl")
            if not os.path.exists(f):
                return None
            out = {}
            with open(f) as fh:
                for line in fh:
                    r = json.loads(line)
                    if "error" in r or "choice_logits" not in r:
                        continue
                    z = np.asarray(r["choice_logits"])
                    out[r["item_id"]] = (int(z.argmax()), r["label"])
            return out or None

        def acc_of(path):
            d_ = preds_of(path)
            if not d_:
                return None
            return (sum(a == y for a, y in d_.values()) / len(d_), len(d_))

        def flips_vs(path, ref="independent"):
            """Disagreement with the reference path on the *same* items.

            The parity check samples 400 readouts; this is every item the
            accuracy column is computed on, so the two numbers in a row come
            from one sample rather than two.
            """
            a_, b_ = preds_of(path), preds_of(ref)
            if not a_ or not b_:
                return None
            keys = set(a_) & set(b_)
            if not keys:
                return None
            diff = sum(a_[k][0] != b_[k][0] for k in keys)
            return diff / len(keys), diff, len(keys)

        par = bench["parity"]
        # ordered so the two factors read off the rows: sharing down the
        # groups, batching within each pair
        rows = [("independent", "independent", "---", "---"),
                ("independent_batch", "independent", "---", "yes"),
                ("vision_cache", "vision cache", "vision", "---"),
                ("vision_cache_batch", "vision cache", "vision", "yes"),
                ("prefix_share", "prefix share", "prefix", "---"),
                ("prefix_share_batch", "prefix share", "prefix", "yes"),
                ("gen_one_token_each", "generate, 1 token/q", "---", "---"),
                ("gen_compact_joint", "generate, joint", "---", "---")]
        base = acc_of("independent")
        with open(f"{args.out_dir}/tab_cost.tex", "w") as fh:
            fh.write("\\begin{table*}[t]\n\\centering\\scriptsize\n"
                     "\\setlength{\\tabcolsep}{3pt}\n"
                     "\\begin{tabular}{lllrrr" + "r" * len(show_N) + "rr}\n\\toprule\n"
                     " & & & \\multicolumn{3}{c}{Decision quality} & "
                     f"\\multicolumn{{{len(show_N)}}}{{c}}{{Amortized time / question (ms)}} & & \\\\\n"
                     f"\\cmidrule(lr){{4-6}}\\cmidrule(lr){{7-{6+len(show_N)}}}\n"
                     "Path & Reuses & Batches & Accuracy & $\\Delta$ & disagree & "
                     + " & ".join(f"$N{{=}}{n}$" for n in show_N)
                     + " & Q/s & GiB \\\\\n\\midrule\n")
            for key, lbl, shares, batches in rows:
                a = acc_of(key)
                if a is None:
                    acc_c, d_c, fl_c = "--", "--", "--"
                else:
                    acc_c = f"{a[0]:.4f}"
                    d_c = "---" if key == "independent" or base is None else f"{a[0]-base[0]:+.4f}"
                    fv = None if key == "independent" else flips_vs(key)
                    fl_c = "---" if key == "independent" else (
                        f"{fv[1]}/{fv[2]:,}" if fv else "--")
                lat = [f"{at(key, n):.1f}" if at(key, n) else "--" for n in show_N]
                big = at(key, max(Ns))
                qs = f"{1000.0/big:.0f}" if big else "--"
                mem = at(key, max(Ns), "peak_gib")
                fh.write(" & ".join([lbl, shares, batches, acc_c, d_c, fl_c] + lat
                                    + [qs, f"{mem:.2f}" if mem else "--"]) + " \\\\\n")
                if key == "prefix_share_batch":
                    fh.write("\\midrule\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{What sharing buys, what batching buys, and what either costs. "
                     "\\emph{Reuses} and \\emph{Batches} say what each row shares across the $N$ "
                     "questions and whether it runs them together. $\\Delta$ and the "
                     "disagreement count are against the independent path on the same items. "
                     "The generation rows answer by emitting a token, so their accuracy is a "
                     "different measurement. Times are synchronized warm wall-clock group intervals "
                     "divided by $N$. They start from an in-memory decoded image and extracted "
                     "records, include processor/tokenization, transfers and path execution, and "
                     "exclude image decode, record construction, disk, network and queueing; they "
                     "are not independent-request response latencies.}"
                     "\\label{tab:cost}\\end{table*}\n")
            if base:
                M.add("VDMpathAccN", f"{base[1]:,}")
                M.add("VDMpathAcc", f"{base[0]:.4f}")
                readout = [r[0] for r in rows if not r[0].startswith("gen_")]
                accs = {k: acc_of(k) for k in readout}
                accs = {k: v for k, v in accs.items() if v}
                same = [k for k, v in accs.items() if abs(v[0] - base[0]) < 5e-5]
                worst = max((abs(v[0] - base[0]) for v in accs.values()), default=0.0)
                M.add("VDMpathAccSame", f"{len(same)} of {len(accs)}")
                M.add("VDMpathAccWorst", f"{worst:.4f}")
            for nm, key in (("VDMdisagreeShare", "prefix_share"),
                            ("VDMdisagreeBatch", "prefix_share_batch")):
                fv = flips_vs(key)
                if fv:
                    M.add(nm, f"{fv[1]} of {fv[2]:,}")
        nmax = max(Ns)
        c_ser = at("independent", nmax)
        c_indb = at("independent_batch", nmax)
        c_shb = at("prefix_share_batch", nmax)
        if c_ser and c_indb and c_shb:
            M.add("VDMgainTotal", f"{c_ser/c_shb:.1f}$\\times$")
            M.add("VDMgainBatching", f"{c_ser/c_indb:.1f}$\\times$")
            M.add("VDMgainSharing", f"{c_indb/c_shb:.1f}$\\times$")
            M.add("VDMcostIndepBatch", f"{c_indb:.1f}\\,ms")
        big_ind, big_bat = at("independent", max(Ns)), at("prefix_share_batch", max(Ns))
        if big_ind and big_bat:
            M.add("VDMthroughputGain", f"{big_ind/big_bat:.1f}$\\times$")
            M.add("VDMqpsBatched", f"{1000.0/big_bat:.0f}")
            M.add("VDMqpsIndependent", f"{1000.0/big_ind:.0f}")
        for nm, key in (("VDMbatchSharePeakMem", "prefix_share_batch"),
                        ("VDMindependentPeakMem", "independent")):
            m_ = at(key, max(Ns), "peak_gib")
            if m_:
                M.add(nm, f"{m_:.2f}\\,GiB")

    # ---------------- per-benchmark quality, the new main table -------------
    bm = load(args.benchmarks)
    if bm:
        V = bm["variants"]
        seen = bm["seen_in_training"]
        order = [("B1", "4B original backbone", "LM"),
                 ("a2", "4B answer SFT", "LM"),
                 ("B1_8b", "8B original backbone", "LM"),
                 ("a2_8b", "8B answer SFT", "LM"),
                 ("b2k", "4B decision CE", "head"),
                 ("mk", "\\quad + sufficiency", "head"),
                 ("b2", "4B decision CE, $K\\le4$", "head")]

        def _acc(entry):
            """Per-benchmark entries are dicts; the macro average is a float."""
            if entry is None:
                return None
            return entry["accuracy"] if isinstance(entry, dict) else float(entry)

        def agg_b(prefix, bench):
            vals = [a for a in (_acc(V[n].get(bench)) for n in V
                                if n.split("_s")[0] == prefix) if a is not None]
            if not vals:
                return None
            return (float(np.mean(vals)),
                    float(np.std(vals)) if len(vals) > 1 else 0.0, len(vals))

        def cell(t, d=3):
            if t is None:
                return "--"
            return f"{t[0]:.{d}f}" + (f"\\,$\\pm$\\,{t[1]:.{d}f}" if t[2] > 1 else "")

        benches = bm["benchmarks"]
        with open(f"{args.out_dir}/tab_benchmarks.tex", "w") as fh:
            fh.write("\\begin{table*}[t]\n\\centering\\scriptsize\n"
                     "\\begin{tabular}{llc" + "r" * (len(benches) + 1) + "}\n\\toprule\n"
                     "System & Readout & Seeds & "
                     + " & ".join(
                         b.replace("-Choice", "") + ("" if seen.get(b) else "$^\\dagger$")
                         for b in benches)
                     + " & Macro \\\\\n\\midrule\n")
            for key, lbl, readout in order:
                if not any(n.split("_s")[0] == key for n in V):
                    continue
                cells = [cell(agg_b(key, b)) for b in benches]
                mac = agg_b(key, "macro_avg")
                nseed = mac[2] if mac else 0
                fh.write(" & ".join([lbl, readout, f"{nseed}"] + cells
                                    + [cell(mac)]) + " \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{Accuracy per benchmark. $^\\dagger$ marks a task no "
                     "post-training in this paper ever saw. The macro average weights the four "
                     "benchmarks equally, so the largest or easiest cannot carry it. The "
                     "\\emph{Readout} column gives the output each system is read through, which is the one "
                     "it was trained for: the backbone's own LM head, or a decision head. "
                     "\\emph{Original backbone} denotes the instruction-tuned checkpoint before "
                     "any additional task adaptation in this paper. "
                     "$\\pm$ is the standard deviation across seeds. The last row is the same decision "
                     "training on data that only ever presented $K\\le4$ options.}"
                     "\\label{tab:benchmarks}\\end{table*}\n")

        SPELL2 = {"B1": "Bone", "a2": "Atwo", "b2k": "Btwok", "mk": "Mk", "b2": "Btwofixed"}
        for key, nice in SPELL2.items():
            t = agg_b(key, "macro_avg")
            if t:
                M.add(f"VDMmacro{nice}", f"{t[0]:.3f}")
                if t[2] > 1:
                    vv = [V[n]["macro_avg"] for n in V if n.split("_s")[0] == key]
                    M.add(f"VDMmacro{nice}Range", f"{min(vv):.3f}--{max(vv):.3f}")
            t = agg_b(key, "TextVQA-Choice")
            if t:
                M.add(f"VDMtextvqa{nice}", f"{t[0]:.3f}")
        a_, b_ = agg_b("a2", "macro_avg"), agg_b("b2k", "macro_avg")
        if a_ and b_:
            M.add("VDMheadDelta", f"{b_[0]-a_[0]:+.3f}")

    # ------------------------- numerical root cause -------------------------
    pr = load(args.precision)
    if pr and "bfloat16" in pr and "float32" in pr:
        for tag, nice in (("bfloat16", "Bf"), ("float32", "Fp")):
            sm = pr[tag]["summary"]
            for path, pn in (("prefix_share_batch", "Share"), ("independent_batch", "Batch"),
                             ("vision_cache", "Cache")):
                if path in sm:
                    M.add(f"VDMprec{nice}{pn}Max", sci(sm[path]["max"]))
                    M.add(f"VDMprec{nice}{pn}Flip", f"{sm[path]['flip_rate']:.4f}")
        w = pr.get("worst_items") or []
        if w:
            M.add("VDMworstMargin", f"{w[0]['margin']:.3f}")
            M.add("VDMworstDprob", f"{w[0]['dprob_prefix_share_batch']:.3f}")
            zero = sum(1 for r in w if r["margin"] < 0.01)
            M.add("VDMworstAtTie", f"{zero} of {len(w)}")

    # ------------------------- what a bigger backbone costs ------------------
    b8 = load(args.bench_8b)
    if bm and bench and b8:
        V = bm["variants"]
        sw4, sw8 = bench["sweep"], b8["sweep"]
        nmax = max(r["N"] for r in sw4)

        def at(sw, path, n, key="per_question_ms"):
            r = next((x for x in sw if x["N"] == n and x["path"] == path), None)
            return r[key] if r else None

        def mac(prefix):
            v = [V[k]["macro_avg"] for k in V
                 if k.split("_s")[0] == prefix and V[k].get("macro_avg")]
            return (float(np.mean(v)), min(v), max(v)) if v else None

        rows = [("Qwen3-VL-4B", "a2", sw4), ("Qwen3-VL-8B", "a2_8b", sw8)]
        with open(f"{args.out_dir}/tab_scale.tex", "w") as fh:
            fh.write("\\begin{table}[t]\n\\centering\\footnotesize\n"
                     "\\begin{tabular}{lrrrr}\n\\toprule\n"
                     "Backbone & Macro & amort. ms/q & Q/s & GiB \\\\\n\\midrule\n")
            for lbl, key, sw in rows:
                m_ = mac(key)
                c = at(sw, "prefix_share_batch", nmax)
                g = at(sw, "prefix_share_batch", nmax, "peak_gib")
                fh.write(f"{lbl} & {m_[0]:.3f} & {c:.1f} & {1000/c:.0f} & {g:.1f} \\\\\n")
            fh.write("\\bottomrule\\end{tabular}\n"
                     "\\caption{What the larger backbone costs, both answer-SFT, both on the "
                     f"shared batched path at $N{{=}}{nmax}$ on the same GPU at the same precision "
                     "and visual budget. Macro accuracy is the mean over three seeds.}"
                     "\\label{tab:scale}\\end{table}\n")
        m4, m8 = mac("a2"), mac("a2_8b")
        c4 = at(sw4, "prefix_share_batch", nmax)
        c8 = at(sw8, "prefix_share_batch", nmax)
        g4 = at(sw4, "prefix_share_batch", nmax, "peak_gib")
        g8 = at(sw8, "prefix_share_batch", nmax, "peak_gib")
        if m4 and m8:
            M.add("VDMscaleGain", f"{m8[0]-m4[0]:+.3f}")
            M.add("VDMmacroEightSFT", f"{m8[0]:.3f}")
            M.add("VDMmacroEightRange", f"{m8[1]:.3f}--{m8[2]:.3f}")
            M.add("VDMmacroFourRange", f"{m4[1]:.3f}--{m4[2]:.3f}")
            M.add("VDMmacroEightBase", f"{mac('B1_8b')[0]:.3f}")
        if c4 and c8:
            M.add("VDMscaleLatency", f"{(c8/c4-1)*100:.0f}\\%")
            M.add("VDMcostEightShared", f"{c8:.1f}\\,ms")
            M.add("VDMscaleMem", f"{(g8/g4-1)*100:.0f}\\%")
            M.add("VDMspeedupEight",
                  f"{at(sw8,'independent',nmax)/c8:.1f}$\\times$")

    M.write(f"{args.out_dir}/macros.tex")
    print(f"wrote {len(M.lines)} macros and tables -> {args.out_dir}")


if __name__ == "__main__":
    main()
